version: 2.1

jobs:
  build:
    docker:
      - image: node:22.2.0

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-9 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store

  lint:
    docker:
      - image: node:22.2.0
    steps:
      - run:
          name: Lint
          command: |
            pnpm lint

  unit_test:
    docker:
      - image: node:22.2.0
    steps:
      - run:
          name: Test
          command: |
            pnpm test

workflows:
  validation:
    jobs:
      - build
      - lint:
          requires:
            - build
      - unit_test:
          requires:
            - build
