import React, { useEffect, useMemo, useState } from "react";
import { FormProvider, useForm, useWatch } from "react-hook-form";
import { useAuth } from "@clerk/nextjs";
import { zodResolver } from "@hookform/resolvers/zod";
import * as Sentry from "@sentry/nextjs";
import { toast } from "sonner";
import { useDebounceValue } from "usehooks-ts";
import type * as z from "zod";

import { Button } from "@components/ui/button";
import {
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@components/ui/form";
import { Input } from "@components/ui/input";
import { VStack } from "@components/VStack";
import { ResourceFormPreview } from "@modules/songs/forms/CreateResourceForm/ResourceFormPreview";
import { trpc } from "@lib/trpc";
import { type Resource } from "@lib/types";
import { insertResourceSchema } from "@lib/types/zod";
import { isPreviewableResourceUrl } from "@lib/urls/resourcePreviewUrl";
import { cn } from "@lib/utils";

const RESOURCE_URL_PREVIEW_DEBOUNCE_MS = 400;
const RESOURCE_PREVIEW_METADATA_STALE_TIME_MS = 5 * 60 * 1000;

const resourceFormSchema = insertResourceSchema.pick({
  title: true,
  url: true,
});

type ResourceFormFields = z.infer<typeof resourceFormSchema>;

type SharedResourceFormProps = {
  className?: string;
  layout?: "default" | "compact";
  onCancel?: () => void;
  onSuccess: () => void;
};

type CreateResourceFormProps = {
  mode: "create";
  songId: string;
  organizationId: string;
  resource?: never;
};

type UpdateResourceFormProps = {
  mode: "edit";
  resource: Resource;
  songId?: never;
  organizationId?: never;
};

type ResourceFormProps = (CreateResourceFormProps | UpdateResourceFormProps) &
  SharedResourceFormProps;

export const ResourceForm: React.FC<ResourceFormProps> = ({
  className,
  layout = "default",
  onCancel,
  onSuccess,
  ...props
}) => {
  const { userId } = useAuth();
  const apiUtils = trpc.useUtils();

  const resource = props.resource;
  const songId = resource?.songId ?? props.songId;
  const requestedOrganizationId =
    resource?.organizationId ?? props.organizationId;

  const createResourceMutation = trpc.resource.create.useMutation();
  const updateResourceMutation = trpc.resource.update.useMutation();

  const defaultValues = useMemo<ResourceFormFields>(
    () => ({
      title: resource?.title ?? "",
      url: resource?.url ?? "",
    }),
    [resource?.title, resource?.url],
  );

  const resourceForm = useForm<ResourceFormFields>({
    resolver: zodResolver(resourceFormSchema),
    defaultValues,
    mode: "onSubmit",
    reValidateMode: "onChange",
  });
  const { clearErrors, reset, trigger } = resourceForm;

  useEffect(() => {
    reset(defaultValues);
  }, [defaultValues, reset]);

  const watchedTitle = useWatch({
    control: resourceForm.control,
    name: "title",
  });
  const watchedUrl = useWatch({
    control: resourceForm.control,
    name: "url",
  });
  const [debouncedUrl] = useDebounceValue(
    watchedUrl ?? "",
    RESOURCE_URL_PREVIEW_DEBOUNCE_MS,
  );
  const [autoGeneratedTitle, setAutoGeneratedTitle] = useState<{
    title: string;
    url: string;
  } | null>(null);
  const trimmedUrl = (watchedUrl ?? "").trim();
  const trimmedDebouncedUrl = debouncedUrl.trim();
  const canPreviewUrl = isPreviewableResourceUrl(trimmedUrl);
  const isWaitingForPreviewDebounce =
    canPreviewUrl && trimmedUrl !== trimmedDebouncedUrl;
  const previewMetadataQuery = trpc.resource.previewMetadata.useQuery(
    {
      organizationId: requestedOrganizationId ?? "",
      url: trimmedDebouncedUrl || "https://example.com",
    },
    {
      enabled:
        !!requestedOrganizationId &&
        canPreviewUrl &&
        !isWaitingForPreviewDebounce,
      staleTime: RESOURCE_PREVIEW_METADATA_STALE_TIME_MS,
      refetchOnWindowFocus: false,
    },
  );
  const previewMetadataForCurrentUrl =
    canPreviewUrl && trimmedUrl === trimmedDebouncedUrl
      ? previewMetadataQuery.data
      : undefined;
  const suggestedTitleForCurrentUrl =
    previewMetadataForCurrentUrl?.title?.trim() ?? null;
  const isNameAutoGeneratedForCurrentUrl =
    autoGeneratedTitle?.url === trimmedDebouncedUrl &&
    autoGeneratedTitle.title === suggestedTitleForCurrentUrl &&
    !!suggestedTitleForCurrentUrl &&
    watchedTitle === suggestedTitleForCurrentUrl;

  // Clear the generated name when the source URL is removed, but preserve custom names.
  useEffect(() => {
    if (trimmedUrl.length > 0 || !autoGeneratedTitle) {
      return;
    }

    if (resourceForm.getValues("title") !== autoGeneratedTitle.title) {
      return;
    }

    resourceForm.setValue("title", "", {
      shouldDirty: false,
      shouldTouch: false,
      shouldValidate: true,
    });
    setAutoGeneratedTitle(null);
  }, [autoGeneratedTitle, resourceForm, trimmedUrl]);

  // Keep the name suggestion in sync until the user replaces it with custom text.
  useEffect(() => {
    const currentTitle = (resourceForm.getValues("title") ?? "").trim();

    if (
      !suggestedTitleForCurrentUrl &&
      autoGeneratedTitle &&
      autoGeneratedTitle.url !== trimmedDebouncedUrl &&
      currentTitle === autoGeneratedTitle.title
    ) {
      resourceForm.setValue("title", "", {
        shouldDirty: false,
        shouldTouch: false,
        shouldValidate: true,
      });
      setAutoGeneratedTitle(null);
      return;
    }

    if (!suggestedTitleForCurrentUrl) {
      return;
    }

    const isCurrentSuggestionStored =
      autoGeneratedTitle?.title === suggestedTitleForCurrentUrl &&
      autoGeneratedTitle.url === trimmedDebouncedUrl;

    if (
      currentTitle === suggestedTitleForCurrentUrl &&
      isCurrentSuggestionStored
    ) {
      return;
    }

    const shouldSuggestTitle =
      currentTitle.length === 0 || autoGeneratedTitle !== null;

    if (!shouldSuggestTitle) {
      return;
    }

    resourceForm.setValue("title", suggestedTitleForCurrentUrl, {
      shouldDirty: false,
      shouldTouch: false,
      shouldValidate: true,
    });
    setAutoGeneratedTitle({
      title: suggestedTitleForCurrentUrl,
      url: trimmedDebouncedUrl,
    });
  }, [
    autoGeneratedTitle,
    resourceForm,
    suggestedTitleForCurrentUrl,
    trimmedDebouncedUrl,
    watchedTitle,
  ]);

  // TODO: handle if there is no user data (assume this will be handled before it reaches here though?)
  const { data: userData } = trpc.user.getUser.useQuery(
    {
      userId: userId!, // using non-null assertion since this query is only enabled if userId is not null
    },
    {
      enabled: !!userId,
    },
  );

  if (!userId) {
    return null;
  }

  const {
    formState: { errors, isDirty, isSubmitting, submitCount },
  } = resourceForm;

  const handleResourceSubmit = async (formValues: ResourceFormFields) => {
    const actionErrorCopy = resource ? "update" : "link";
    const actionCopy = resource
      ? "Updating resource..."
      : "Linking resource...";
    const toastId = toast.loading(actionCopy);

    if (!userData) {
      Sentry.captureException(new Error("No user data available"));
      toast.error(`Could not ${actionErrorCopy} resource: invalid user`, {
        id: toastId,
      });

      return;
    }

    if (!songId || !requestedOrganizationId) {
      Sentry.captureException(new Error("No resource organization found"));
      toast.error(
        `Could not ${actionErrorCopy} resource: invalid team context`,
        {
          id: toastId,
        },
      );

      return;
    }

    const organizationMembership = userData.memberships.find(
      (membership) => membership.organizationId === requestedOrganizationId,
    );
    const organizationId = organizationMembership?.organizationId;

    if (!organizationId) {
      Sentry.captureException(new Error("No organization membership found"));
      toast.error(
        `Could not ${actionErrorCopy} resource: invalid team membership`,
        {
          id: toastId,
        },
      );

      return;
    }

    try {
      if (resource) {
        await updateResourceMutation.mutateAsync({
          resourceId: resource.id,
          organizationId,
          title: formValues.title,
          url: formValues.url,
        });
      } else {
        await createResourceMutation.mutateAsync({
          songId,
          organizationId,
          title: formValues.title,
          url: formValues.url,
        });
      }

      await apiUtils.resource.getBySongId.invalidate({
        songId,
        organizationId,
      });

      toast.success(resource ? "Resource was updated" : "Resource was linked", {
        id: toastId,
      });
      onSuccess();
      reset(resource ? formValues : defaultValues);
    } catch (error) {
      Sentry.captureException(error);

      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";

      toast.error(`Could not ${actionErrorCopy} resource: ${errorMessage}`, {
        id: toastId,
      });
    }
  };

  const shouldSubmitButtonBeDisabled =
    isSubmitting ||
    previewMetadataQuery.isFetching ||
    isWaitingForPreviewDebounce ||
    Object.keys(errors).length > 0 ||
    Boolean(resource && !isDirty);
  const submitText = resource ? "Save changes" : "Link resource";
  const isCompact = layout === "compact";

  return (
    <FormProvider {...resourceForm}>
      <form onSubmit={resourceForm.handleSubmit(handleResourceSubmit)}>
        <VStack className={cn("gap-6", isCompact && "gap-3", className)}>
          <ResourceFormPreview
            resource={resource}
            title={watchedTitle ?? ""}
            url={watchedUrl ?? ""}
            previewMetadata={previewMetadataForCurrentUrl}
            isLoading={
              isWaitingForPreviewDebounce || previewMetadataQuery.isFetching
            }
          />
          <FormField
            control={resourceForm.control}
            name="url"
            render={({ field }) => (
              <FormItem>
                <FormLabel>URL *</FormLabel>
                <FormControl>
                  <Input
                    {...field}
                    size="medium"
                    onChange={(event) => {
                      field.onChange(event);

                      if (!errors.url && submitCount === 0) {
                        return;
                      }

                      if (event.target.value.trim()) {
                        void trigger("url");
                        return;
                      }

                      clearErrors("url");
                    }}
                    onBlur={(event) => {
                      field.onBlur();

                      if (event.target.value.trim()) {
                        void trigger("url");
                        return;
                      }

                      clearErrors("url");
                    }}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={resourceForm.control}
            name="title"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Name</FormLabel>
                <FormControl>
                  <Input
                    {...field}
                    value={field.value ?? ""}
                    size="medium"
                    className={cn(
                      isNameAutoGeneratedForCurrentUrl && "text-slate-500",
                    )}
                    onChange={(event) => {
                      setAutoGeneratedTitle(null);
                      field.onChange(event);
                    }}
                  />
                </FormControl>
                {isNameAutoGeneratedForCurrentUrl && (
                  <FormDescription className="text-xs text-slate-500">
                    Suggested from the page title, but feel free to rename it.
                  </FormDescription>
                )}
                <FormMessage />
              </FormItem>
            )}
          />
          <div
            className={cn(
              "mt-4 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end",
              isCompact && "mt-1",
            )}
          >
            {!!onCancel && (
              <Button type="button" variant="ghost" onClick={onCancel}>
                Cancel
              </Button>
            )}
            <Button
              type="submit"
              isLoading={isSubmitting}
              disabled={shouldSubmitButtonBeDisabled}
            >
              {submitText}
            </Button>
          </div>
        </VStack>
      </form>
    </FormProvider>
  );
};
