import React from "react";

import type { ResourceFormProps } from "./resourceFormTypes";
import { ResourceFormView } from "./ResourceFormView";
import { useResourceFormController } from "./useResourceFormController";

export const ResourceForm: React.FC<ResourceFormProps> = ({
  className,
  layout = "default",
  onCancel,
  onSuccess,
  ...props
}) => {
  const controller = useResourceFormController({
    ...props,
    onSuccess,
  });

  if (!controller.isAuthenticated) {
    return null;
  }

  return (
    <ResourceFormView
      className={className}
      form={controller.form}
      isNameAutoGenerated={controller.autoTitle.isNameAutoGenerated}
      isPreviewLoading={controller.preview.isLoading}
      layout={layout}
      onCancel={onCancel}
      onClearAutoGeneratedTitle={controller.autoTitle.clearAutoGeneratedTitle}
      onSubmit={controller.handleSubmit}
      previewMetadata={controller.preview.previewMetadata}
      resource={controller.resource}
      submitButton={controller.submitButton}
      watchedTitle={controller.watchedTitle}
      watchedUrl={controller.watchedUrl}
    />
  );
};
