import { FormProvider, type UseFormReturn } from "react-hook-form";

import { Button } from "@components/ui/button";
import {
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@components/ui/form";
import { Input } from "@components/ui/input";
import { VStack } from "@components/VStack";
import { type RouterOutputs } from "@lib/trpc";
import type { Resource } from "@lib/types";
import { cn } from "@lib/utils";

import { ResourceFormPreview } from "./ResourceFormPreview";
import type { ResourceFormFields } from "./resourceFormSchema";

type ResourceFormViewProps = {
  className?: string;
  form: UseFormReturn<ResourceFormFields>;
  isNameAutoGenerated: boolean;
  layout: "default" | "compact";
  onCancel?: () => void;
  onClearAutoGeneratedTitle: () => void;
  onSubmit: (formValues: ResourceFormFields) => Promise<void>;
  previewMetadata?: RouterOutputs["resource"]["previewMetadata"];
  resource?: Resource;
  submitButton: {
    isDisabled: boolean;
    isLoading: boolean;
    text: string;
  };
  watchedTitle: string | null | undefined;
  watchedUrl: string | null | undefined;
  isPreviewLoading: boolean;
};

export const ResourceFormView = ({
  className,
  form,
  isNameAutoGenerated,
  isPreviewLoading,
  layout,
  onCancel,
  onClearAutoGeneratedTitle,
  onSubmit,
  previewMetadata,
  resource,
  submitButton,
  watchedTitle,
  watchedUrl,
}: ResourceFormViewProps) => {
  const isCompact = layout === "compact";
  const {
    clearErrors,
    formState: { errors, submitCount },
    trigger,
  } = form;

  return (
    <FormProvider {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)}>
        <VStack className={cn("gap-6", isCompact && "gap-3", className)}>
          <ResourceFormPreview
            resource={resource}
            title={watchedTitle ?? ""}
            url={watchedUrl ?? ""}
            previewMetadata={previewMetadata}
            isLoading={isPreviewLoading}
          />
          <FormField
            control={form.control}
            name="url"
            render={({ field }) => (
              <FormItem>
                <FormLabel>URL *</FormLabel>
                <FormControl>
                  <Input
                    {...field}
                    size="medium"
                    onChange={(event) => {
                      field.onChange(event);

                      if (!errors.url && submitCount === 0) {
                        return;
                      }

                      if (event.target.value.trim()) {
                        void trigger("url");
                        return;
                      }

                      clearErrors("url");
                    }}
                    onBlur={(event) => {
                      field.onBlur();

                      if (event.target.value.trim()) {
                        void trigger("url");
                        return;
                      }

                      clearErrors("url");
                    }}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name="title"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Name</FormLabel>
                <FormControl>
                  <Input
                    {...field}
                    value={field.value ?? ""}
                    size="medium"
                    className={cn(isNameAutoGenerated && "text-slate-500")}
                    onChange={(event) => {
                      onClearAutoGeneratedTitle();
                      field.onChange(event);
                    }}
                  />
                </FormControl>
                {isNameAutoGenerated && (
                  <FormDescription className="text-xs text-slate-500">
                    Suggested from the page title, but feel free to rename it.
                  </FormDescription>
                )}
                <FormMessage />
              </FormItem>
            )}
          />
          <div
            className={cn(
              "mt-4 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end",
              isCompact && "mt-1",
            )}
          >
            {!!onCancel && (
              <Button type="button" variant="ghost" onClick={onCancel}>
                Cancel
              </Button>
            )}
            <Button
              type="submit"
              isLoading={submitButton.isLoading}
              disabled={submitButton.isDisabled}
            >
              {submitButton.text}
            </Button>
          </div>
        </VStack>
      </form>
    </FormProvider>
  );
};
