import { useEffect, useState } from "react";
import type { UseFormReturn } from "react-hook-form";

import type { ResourceFormFields } from "./resourceFormSchema";

type AutoGeneratedTitle = {
  title: string;
  url: string;
};

type UseResourceFormAutoTitleProps = {
  form: UseFormReturn<ResourceFormFields>;
  suggestedTitle: string | null;
  debouncedUrl: string;
  currentUrl: string;
  watchedTitle: string | null | undefined;
};

export const useResourceFormAutoTitle = ({
  form,
  suggestedTitle,
  debouncedUrl,
  currentUrl,
  watchedTitle,
}: UseResourceFormAutoTitleProps) => {
  const [autoGeneratedTitle, setAutoGeneratedTitle] =
    useState<AutoGeneratedTitle | null>(null);

  useEffect(() => {
    if (currentUrl.length > 0 || !autoGeneratedTitle) {
      return;
    }

    if (form.getValues("title") !== autoGeneratedTitle.title) {
      return;
    }

    form.setValue("title", "", {
      shouldDirty: false,
      shouldTouch: false,
      shouldValidate: true,
    });
    queueMicrotask(() => {
      setAutoGeneratedTitle(null);
    });
  }, [autoGeneratedTitle, currentUrl, form]);

  useEffect(() => {
    const currentTitle = (form.getValues("title") ?? "").trim();

    if (
      !suggestedTitle &&
      autoGeneratedTitle &&
      autoGeneratedTitle.url !== debouncedUrl &&
      currentTitle === autoGeneratedTitle.title
    ) {
      form.setValue("title", "", {
        shouldDirty: false,
        shouldTouch: false,
        shouldValidate: true,
      });
      queueMicrotask(() => {
        setAutoGeneratedTitle(null);
      });
      return;
    }

    if (!suggestedTitle) {
      return;
    }

    const isCurrentSuggestionStored =
      autoGeneratedTitle?.title === suggestedTitle &&
      autoGeneratedTitle.url === debouncedUrl;

    if (currentTitle === suggestedTitle && isCurrentSuggestionStored) {
      return;
    }

    const shouldSuggestTitle =
      currentTitle.length === 0 || autoGeneratedTitle !== null;

    if (!shouldSuggestTitle) {
      return;
    }

    form.setValue("title", suggestedTitle, {
      shouldDirty: false,
      shouldTouch: false,
      shouldValidate: true,
    });
    queueMicrotask(() => {
      setAutoGeneratedTitle({
        title: suggestedTitle,
        url: debouncedUrl,
      });
    });
  }, [autoGeneratedTitle, debouncedUrl, form, suggestedTitle, watchedTitle]);

  const isNameAutoGenerated =
    autoGeneratedTitle?.url === debouncedUrl &&
    autoGeneratedTitle.title === suggestedTitle &&
    !!suggestedTitle &&
    watchedTitle === suggestedTitle;

  return {
    isNameAutoGenerated,
    clearAutoGeneratedTitle: () => setAutoGeneratedTitle(null),
  };
};
